name: Full Site Migration
on:
  workflow_dispatch:
jobs:
  migrate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Migrate
        run: echo "Migration"
